let a=20;
let b=10;

//arthmetic operators
let sum=a+b; 
let sub=a-b;
let mul=a*b;
let div=a/b;
let mod=a%b;

//Output
console.log("Sum: "+sum);
console.log("Subtraction: "+sub);
console.log("Multiplication: "+mul);
console.log("Division: "+div);
console.log("Modulus: "+mod);
//r= 1 is odd and r=0 is even
console.log(a **b) ; //Exponentiation: a raised to the power of b

// -------
console.log(a % b); // Modulus operaor - it gives -> Remainder
console.log(13 % 7);

console.log(100 % 2);
console.log(101 % 2);
console.log(103 % 2);

//  n%2 == 1 - odd number, [ n%2 == 0 , even]

console.log(2 ** 3); // exponetial a^b
console.log(a ** b); // exponetial a^b 10^3

// Increment and Decrement Operators
// a++, b-- (learn about the, one more class)
let firstname = "Pramod";
